name: Release AutoTag
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
      - experimental

    paths-ignore:
      - 'docs/**'
      - "howto/**"
      - "*.md"
      - ".clang-format"      

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      
    env:
      version: 24.11.0
      version-suffix: ${{ !contains(github.ref_name,'master') && 'alpha' || 'Release' }}
      prerelease: ${{ !contains(github.ref_name,'master') }}

    steps:
      - uses: actions/checkout@v4
            
      - name: set git short sha
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short=8 HEAD)"    >> $GITHUB_OUTPUT
          echo "release_hm=$(date +'%y%m%d')"              >> $GITHUB_OUTPUT
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{env.version}}-${{env.version-suffix}}.${{ steps.vars.outputs.sha_short }}
